#!/usr/bin/env bash
# Kali Linux Podman container module for lolterm
# Provides a full Kali tool environment via a rootless Podman container
# with native shell wrapper integration.

install_kali_container() {
  section "Setting up Kali Linux container..."

  ensure_podman_installed
  build_kali_image
  create_kali_container
  enable_kali_autostart
  generate_kali_wrappers
  install_kali_shell_integration
  copy_kali_config_to_state

  echo "  Kali container setup complete"
  echo "  Run 'kali-sh' for an interactive Kali shell"
  echo "  Most tools are also available as native commands"
}

ensure_podman_installed() {
  if ! command -v podman &>/dev/null; then
    section "Installing Podman..."
    sudo dnf install -y podman
  fi
}

build_kali_image() {
  local container_dir="$INSTALLER_DIR/install/kali-container"

  section "Building lolterm-kali container image..."

  if podman image exists lolterm-kali &>/dev/null; then
    echo "  Image lolterm-kali already exists — skipping build"
    echo "  Run 'lolterm-kali-rebuild' to rebuild from updated config"
    return 0
  fi

  podman build -t lolterm-kali "$container_dir"
  echo "  Image lolterm-kali built"
}

selinux_volume_flag() {
  if command -v getenforce &>/dev/null && [[ "$(getenforce)" == "Enforcing" ]]; then
    echo ":Z"
  else
    echo ""
  fi
}

create_kali_container() {
  section "Creating kali container..."

  # Remove existing container with this name
  if podman container exists kali &>/dev/null; then
    echo "  Removing existing kali container..."
    podman rm -f kali
  fi

  local vol_flag
  vol_flag="$(selinux_volume_flag)"

  podman create --name kali \
    --network host \
    --privileged \
    -v /tmp/.X11-unix:/tmp/.X11-unix"${vol_flag}" \
    -v "$TARGET_HOME:$TARGET_HOME${vol_flag}" \
    -e DISPLAY \
    lolterm-kali \
    sleep infinity

  echo "  Container 'kali' created"
}

enable_kali_autostart() {
  section "Configuring Kali container autostart..."

  local service_dir="$TARGET_HOME/.config/systemd/user"
  mkdir -p "$service_dir"

  podman generate systemd --name kali --new > "$service_dir/container-kali.service"

  if systemctl --user enable --now container-kali.service 2>/dev/null; then
    echo "  systemd user service enabled and started"
  else
    echo "  Warning: could not enable systemd user service"
    echo "  (no user D-Bus session? systemctl --user not available in this context)"
    echo "  Start manually with: podman start kali"
  fi
}

generate_kali_wrappers() {
  local container_dir="$INSTALLER_DIR/install/kali-container"
  local bindir="$TARGET_HOME/.local/bin"
  mkdir -p "$bindir"

  # Normal tools
  section "Generating normal tool wrappers..."
  generate_wrappers_from_list "$container_dir/tools.txt" "" "$bindir"

  # Privileged tools
  section "Generating privileged tool wrappers..."
  generate_wrappers_from_list "$container_dir/tools-privileged.txt" "--privileged" "$bindir"
}

generate_wrappers_from_list() {
  local list_file="$1"
  local extra_args="$2"
  local bindir="$3"

  if [[ ! -f "$list_file" ]]; then
    echo "  Allowlist not found: $list_file — skipping"
    return 1
  fi

  local count=0
  while IFS= read -r line; do
    # Strip leading/trailing whitespace
    line="${line## }"
    line="${line%% }"
    # Skip blanks and comments
    [[ -z "$line" || "$line" =~ ^# ]] && continue

    cat > "$bindir/$line" <<WRAPPER
#!/usr/bin/env bash
# Kali container wrapper — generated by lolterm
exec podman exec ${extra_args} -it -w "\$PWD" kali "\$(basename "\$0")" "\$@"
WRAPPER
    chmod +x "$bindir/$line"
    count=$((count + 1))
  done < "$list_file"

  echo "  Generated $count wrappers in $bindir"
}

install_kali_shell_integration() {
  section "Adding Kali shell integration..."

  local stamp="# ----- lolterm kali container -----"

  if grep -qF "$stamp" "$TARGET_HOME/.bashrc" 2>/dev/null; then
    echo "  Kali shell integration already present — skipping"
    return 0
  fi

  cat >> "$TARGET_HOME/.bashrc" <<'BASHRC'

# ----- lolterm kali container -----
kali() {
  podman exec -it -w "$PWD" kali "$@"
}
kali-sh() {
  podman exec -it -w "$PWD" kali /bin/bash
}
# ----- /lolterm kali container -----
BASHRC
  echo "  Added kali() and kali-sh() to .bashrc"
}

copy_kali_config_to_state() {
  section "Copying Kali container config to state directory..."

  local src="$INSTALLER_DIR/install/kali-container"
  local dst="$TARGET_HOME/.local/share/lolterm/kali-container"

  mkdir -p "$dst"
  cp -f "$src/Containerfile" "$dst/Containerfile"
  cp -f "$src/packages.txt" "$dst/packages.txt"
  cp -f "$src/tools.txt" "$dst/tools.txt"
  cp -f "$src/tools-privileged.txt" "$dst/tools-privileged.txt"

  echo "  Config copied to $dst"
  echo "  Edit packages.txt and run 'lolterm-kali-rebuild' to add packages"
}
