#!/usr/bin/env bash
# Kali Linux Podman container module for lolterm
# Provides a full Kali tool environment via a rootless Podman container
# with native shell wrapper integration.

install_kali_container() {
  section "Setting up Kali Linux container..."

  ensure_podman_installed
  build_kali_image
  setup_kali_quadlet
  generate_kali_wrappers
  install_kali_shell_integration
  extract_kali_icon
  generate_kali_desktop_entries
  copy_kali_config_to_state

  echo "  Kali container setup complete"
  echo "  Run 'kali-sh' for an interactive Kali shell"
  echo "  Most tools are also available as native commands"
}

ensure_podman_installed() {
  if ! command -v podman &>/dev/null; then
    section "Installing Podman..."
    sudo dnf install -y podman
  fi
}

build_kali_image() {
  local container_dir="$INSTALLER_DIR/install/kali-container"

  section "Building lolterm-kali container image..."

  if podman image exists lolterm-kali &>/dev/null; then
    echo "  Image lolterm-kali already exists — skipping build"
    echo "  Run 'lolterm-kali-rebuild' to rebuild from updated config"
    return 0
  fi

  podman build -t lolterm-kali "$container_dir"
  echo "  Image lolterm-kali built"
}

setup_kali_quadlet() {
  section "Setting up Kali container quadlet..."

  local quadlet_dir="$TARGET_HOME/.config/containers/systemd"

  mkdir -p "$quadlet_dir"
  cp -f "$INSTALLER_DIR/install/kali-container/kali.container" "$quadlet_dir/kali.container"

  # Remove any container created by the old podman create + generate systemd approach
  if podman container exists kali &>/dev/null; then
    podman rm -f kali
  fi

  # Remove the old systemd user service if it exists from a prior install
  rm -f "$TARGET_HOME/.config/systemd/user/container-kali.service"

  # Enable linger so --user services start at boot without requiring login
  loginctl enable-linger "$TARGET_USER" 2>/dev/null || true

  # Use --machine to connect to the user's systemd instance from any context
  # (no D-Bus session needed — systemd-stdio-bridge handles it)
  if systemctl --user --machine="$TARGET_USER@.host" daemon-reload 2>/dev/null; then
    systemctl --user --machine="$TARGET_USER@.host" start kali.service || {
      echo "  Warning: quadlet generated but service did not start"
      echo "  Start manually after login: systemctl --user start kali.service"
    }
    echo "  Quadlet installed and service enabled"
  else
    echo "  Warning: could not connect to user systemd instance (no login session yet?)"
    echo "  The quadlet file is installed at $quadlet_dir/kali.container"
    echo ""
    echo "  After your first login, run:"
    echo "    systemctl --user daemon-reload"
    echo "    systemctl --user start kali.service"
    echo ""
    echo "  Tool wrappers will auto-start the container on first use."
  fi
}

generate_kali_wrappers() {
  local container_dir="$INSTALLER_DIR/install/kali-container"
  local bindir="$TARGET_HOME/.local/bin"
  mkdir -p "$bindir"

  # Normal tools
  section "Generating normal tool wrappers..."
  generate_wrappers_from_list "$container_dir/tools.txt" "" "$bindir"

  # Privileged tools
  section "Generating privileged tool wrappers..."
  generate_wrappers_from_list "$container_dir/tools-privileged.txt" "--privileged" "$bindir"
}

generate_wrappers_from_list() {
  local list_file="$1"
  local extra_args="$2"
  local bindir="$3"

  if [[ ! -f "$list_file" ]]; then
    echo "  Allowlist not found: $list_file — skipping"
    return 1
  fi

  local count=0
  while IFS= read -r line; do
    # Strip leading/trailing whitespace
    line="${line## }"
    line="${line%% }"
    # Skip blanks and comments
    [[ -z "$line" || "$line" =~ ^# ]] && continue

    cat > "$bindir/$line" <<WRAPPER
#!/usr/bin/env bash
# Kali container wrapper — generated by lolterm

# Auto-start container if it exists but isn't running
if ! podman container exists kali 2>/dev/null; then
  echo "Kali container not found. Run: lolterm-kali-rebuild" >&2
  exit 1
fi
if [[ "\$(podman inspect --format '{{.State.Status}}' kali 2>/dev/null)" != "running" ]]; then
  podman start kali >/dev/null
fi

exec podman exec ${extra_args} -it -w "\$PWD" -e DISPLAY -e XAUTHORITY kali "\$(basename "\$0")" "\$@"
WRAPPER
    chmod +x "$bindir/$line"
    count=$((count + 1))
  done < "$list_file"

  echo "  Generated $count wrappers in $bindir"
}

install_kali_shell_integration() {
  section "Adding Kali shell integration..."

  local stamp="# ----- lolterm kali container -----"

  if grep -qF "$stamp" "$TARGET_HOME/.bashrc" 2>/dev/null; then
    echo "  Kali shell integration already present — skipping"
    return 0
  fi

  cat >> "$TARGET_HOME/.bashrc" <<'BASHRC'

# ----- lolterm kali container -----
kali() {
  podman exec -it -w "$PWD" -e DISPLAY -e XAUTHORITY kali "$@"
}
kali-sh() {
  podman exec -it -w "$PWD" -e DISPLAY -e XAUTHORITY kali /bin/bash
}
# ----- /lolterm kali container -----
BASHRC
  echo "  Added kali() and kali-sh() to .bashrc"
}

copy_kali_config_to_state() {
  section "Copying Kali container config to state directory..."

  local src="$INSTALLER_DIR/install/kali-container"
  local dst="$TARGET_HOME/.local/share/lolterm/kali-container"

  mkdir -p "$dst"
  cp -f "$src/Containerfile" "$dst/Containerfile"
  cp -f "$src/kali.container" "$dst/kali.container"
  cp -f "$src/packages.txt" "$dst/packages.txt"
  cp -f "$src/tools.txt" "$dst/tools.txt"
  cp -f "$src/tools-privileged.txt" "$dst/tools-privileged.txt"
  cp -f "$src/tools-gui.txt" "$dst/tools-gui.txt"

  echo "  Config copied to $dst"
  echo "  Edit packages.txt and run 'lolterm-kali-rebuild' to add packages"
}

extract_kali_icon() {
  section "Extracting Kali logo icon from container image..."

  local icon_dir="$TARGET_HOME/.local/share/icons/hicolor/scalable/apps"
  mkdir -p "$icon_dir"

  # Search the image for a scalable Kali logo
  local icon_path
  icon_path="$(podman run --rm lolterm-kali sh -c '
    find /usr/share/icons /usr/share/pixmaps -name "kali*" -path "*/scalable/*" 2>/dev/null | head -1
  ' 2>/dev/null)" || true

  if [[ -n "$icon_path" ]]; then
    podman cp "lolterm-kali:$icon_path" "$icon_dir/kali-logo.svg" 2>/dev/null && {
      echo "  Icon extracted to $icon_dir/kali-logo.svg"
      return 0
    }
  fi

  # Fallback: try non-scalable variants
  icon_path="$(podman run --rm lolterm-kali sh -c '
    find /usr/share/icons /usr/share/pixmaps -name "kali*" 2>/dev/null | head -1
  ' 2>/dev/null)" || true

  if [[ -n "$icon_path" ]]; then
    local ext="${icon_path##*.}"
    podman cp "lolterm-kali:$icon_path" "$icon_dir/kali-logo.$ext" 2>/dev/null && {
      echo "  Icon extracted to $icon_dir/kali-logo.$ext"
      return 0
    }
  fi

  echo "  Warning: Kali logo icon not found in container image — skipping"
  echo "  Desktop entries will use a placeholder icon"
}

generate_kali_desktop_entries() {
  local list_file="$INSTALLER_DIR/install/kali-container/tools-gui.txt"
  local desktop_dir="$TARGET_HOME/.local/share/applications"

  if [[ ! -f "$list_file" ]]; then
    echo "  GUI tools list not found: $list_file — skipping desktop entries"
    return 1
  fi

  section "Generating .desktop entries for GUI tools..."

  mkdir -p "$desktop_dir"
  local count=0

  while IFS= read -r line; do
    # Strip leading/trailing whitespace
    line="${line## }"
    line="${line%% }"
    # Skip blanks and comments
    [[ -z "$line" || "$line" =~ ^# ]] && continue

    # Capitalize first letter for display name
    local first="${line:0:1}"
    local rest="${line:1}"
    local display_name
    display_name="$(tr '[:lower:]' '[:upper:]' <<<"$first")$rest"

    cat > "$desktop_dir/kali-$line.desktop" <<DESKTOP
[Desktop Entry]
Version=1.0
Type=Application
Name=$display_name (Kali)
Comment=Kali container tool
Exec=$TARGET_HOME/.local/bin/$line %F
Icon=kali-logo
Terminal=false
Categories=Security;
DESKTOP

    count=$((count + 1))
  done < "$list_file"

  echo "  Generated $count .desktop entries in $desktop_dir"
}
